version: '2'
services:
  tvmazecache-mongodb:
    image: mongo:5.0.14
    container_name: 'tvmaze-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=shows
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017